# Generated by Django 3.2.5 on 2021-07-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bench',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.DecimalField(decimal_places=10, max_digits=13)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=13)),
                ('average_rating', models.DecimalField(decimal_places=3, max_digits=4)),
                ('nb_voters', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
